apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-local-vol
spec:
  volumeName: "app-flask-local"
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: app-flask-local
#  resources:
#    requests:
#      storage: 30Gi
