apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-flask-pvc
  namespace: app-flask
spec:
  volumeName: "app-flask-pv"
#spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
