apiVersion: v1
kind: Service
metadata:
  name:  app-flask-service
spec:
  selector:
    app:  app-flask
  type:  NodePort
  ports:
  - name:  app-flask
    port:  5000
    protocol: TCP
    targetPort:  5000
    nodePort: 31111