apiVersion: apps/v1
kind: PersistentVolume 
metadata:
  name: app-flask-local
spec:
  local:
    path: /
  nodeAffinity:
  required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - af-svr0
    
